version: '3.7'

services:
  db:
    image: postgres:14.2-alpine3.15
    container_name: metricsGreen_db_test
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-test:/var/lib/postgresql/data

  web:
    build:
      context: ../web
      dockerfile: dev.Dockerfile
    environment:
      REACT_APP_ENV: development
      REACT_APP_SERVER_URL: http://localhost:4001/graphql
      WDS_SOCKET_PORT: 3001
    ports:
      - 3001:3000
    container_name: metricsGreen_web-test
    depends_on:
      - server
    volumes:
      - ../web:/usr/src/web

  server:
    build: ../server
    ports:
      - 4001:4001
    container_name: metricsGreen_server-test
    depends_on:
      - db
    environment:
      PORT: 4001
      DB_HOST: metricsGreen_db_test
      DB_PORT: 5432
      NODE_ENV: development
    volumes:
      - ../server:/usr/src/server

  cypress:
    image: cypress/included:12.6.0
    container_name: cypress
    depends_on:
      - web
    environment:
      CYPRESS_BASE_URL: http://web:3000
      CYPRESS_VERIFY_TIMEOUT: 90000
    working_dir: /e2e
    volumes:
      - ./:/e2e

volumes:
  db-test:
