version: '3.7'

services:
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 3003:8080

  db:
    image: postgres:14.2-alpine3.15
    container_name: metricsGreen_db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
      args:
        REACT_APP_ENV: development
    ports:
      - 3000:3000
    container_name: metricsGreen_web
    volumes:
      - ./web:/usr/src/web

  server:
    build: ./server
    ports:
      - 4000:4000
    container_name: metricsGreen_server
    volumes:
      - ./server:/usr/src/server

volumes:
  db:
