
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 3003:8080

  db:
    image: postgres:14.2-alpine3.15
    container_name: metricsGreen_db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - metricsGreen_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
volumes: 
     metricsGreen_db:
