name: CI/CD pipeline web
on:
  push:
    paths:
      - 'web/**'
      - '.github/**'
jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and upload
        working-directory: web
        run: |
          docker build . -t thomsva/metricsgreen-web:prod
          docker push thomsva/metricsgreen-web:prod
