name: CI/CD pipeline server
on:
  push:
    paths:
      - 'server/**'
      - '.github/**'
jobs:
  eslint:
    uses: ./.github/workflows/eslint.yml
  tests:
    uses: ./.github/workflows/run-tests.yml
  build-and-publish:
    runs-on: ubuntu-20.04
    needs: [ESlint, Run tests]
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and upload
        working-directory: server
        run: |
          docker build . -t thomsva/metricsgreen-server:prod
          docker push thomsva/metricsgreen-server:prod
