name: ESLint
on: [workflow_call]
jobs:
  build-and-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install client and lint
        run: |
          npm ci
          npm run lint
        working-directory: web
      - name: Install server and lint
        run: |
          npm ci
          npm run lint
        working-directory: server
