name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install client modules
    - run: npm ci
      working-directory: web
    - name: Run ESLint on client
    - run: npm run lint
      working-directory: web
    - name: Install server modules
    - run: npm ci
      working-directory: server
    - name: Run ESLint on client
      run: npm run lint
      working-directory: server
