name: Run tests
on:
  workflow_call:

jobs:
  # Run end to end tests using Cypress
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Start test environment
        working-directory: app-test
        run: docker compose up -d db server web
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: app-test
          wait-on: http://localhost:3001, http://localhost:4001
          wait-on-timeout: 300
          quiet: false
          config: video=false
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos
          if-no-files-found: ignore
