name: Cypress tests
on:
  push:

jobs:

  # Run end to end tests using Cypress
  run-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Start test environment
      working-directory: e2e
      run: docker compose up db server web 
    - name: Run Cypress tests
      working-directory: e2e
      run: docker compose up cypress
    - name: Upload screenshots    
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: e2e/cypress/screenshots
    - name: Upload videos    
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-videos
        path: e2e/cypress/videos
        if-no-files-found: ignore